version: '2.2'

services:
  newsapiapp:
    image: newsapi
    container_name: newsapiapp
    depends_on:
      - newsmongodb
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 6060:8080
    networks:
      - newsbridgenetwork
    restart: always

  newsmongodb:
    image: mongo
    container_name: newsmongodb
    expose:
      - 27017
    ports:
      - 27017:27017
    networks:
      - newsbridgenetwork
    volumes:
      - mynewsmongovolume:/data/db
      - mynewsmongovolume:/data/configdb
    restart: always


 
  

networks:
  newsbridgenetwork:
    name: exercises-api_mongobridgenetwork 
    external: true

volumes:
  mynewsmongovolume:
