version: '2.2'

services:
  newsapiapp:
    image: newsapi
    container_name: newsapiapp
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 6060:8080
    networks:
      - newsbridgenetwork
    restart: always


networks:
  newsbridgenetwork:
    name: exercises-api_mongobridgenetwork 
    external: true

volumes:
  mynewsmongovolume:
